import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import * as schema from "./schema";

// Postgres everywhere: `docker compose up -d` locally, Neon (or any Postgres)
// in production — one driver, one code path. Migrations from ./drizzle
// (generated by drizzle-kit) are applied once on first use.
// Cached on globalThis so Next dev doesn't open a pool per compiled route.

const DATABASE_URL =
  process.env.DATABASE_URL ??
  "postgres://nodeledge:nodeledge@localhost:5433/nodeledge";

async function buildDb() {
  const client = postgres(DATABASE_URL, { prepare: false });
  const db = drizzle(client, { schema });
  await migrate(db, { migrationsFolder: "./drizzle" });
  return db;
}

type DB = Awaited<ReturnType<typeof buildDb>>;

const globalForDb = globalThis as unknown as { __nodeledgeDb?: Promise<DB> };

const dbPromise: Promise<DB> = globalForDb.__nodeledgeDb ?? buildDb();
globalForDb.__nodeledgeDb = dbPromise;

export const db: DB = await dbPromise;

export { schema };
